version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-boost:11.1.0-1.76.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - checkout:
          path: /projects/ishiko/cpp/logging
      - run:
          name: Build
          command: cd /projects/ishiko/cpp/logging/build/gnumake && make
